name = "omniai-hub"
main = "_worker.js"
compatibility_date = "2026-09-16"
workers_dev = true
preview_urls = true
keep_vars = true

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "aluna"
database_id = "63a9889f-60a5-4e36-b16f-a3c3e0e18c8d"
